# Generated by Django 5.2.14 on 2026-06-29 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=200, verbose_name='Спортивное название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('rfs_id', models.CharField(blank=True, max_length=50, verbose_name='РФС ID')),
                ('fifa_id', models.CharField(blank=True, max_length=50, verbose_name='FIFA ID')),
                ('ogrn', models.CharField(blank=True, max_length=50, verbose_name='ОГРН')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Общий e-mail')),
                ('aff_name', models.CharField(blank=True, max_length=200, verbose_name='Аффилированные организации')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
