# Generated by Django 5.2.14 on 2026-07-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='rights',
            field=models.IntegerField(default=0, verbose_name='Права доступа (1 - полный доступ)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
