"""
Django settings for lc_clubs project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$ph0_flr@5run$-_8#7uu2!b53u3&+25$6ss*alffh2)b_c(i)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clubs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lc_clubs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'clubs', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lc_clubs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# =============================================
# === НАСТРОЙКИ АУТЕНТИФИКАЦИИ
# =============================================

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================
# НАСТРОЙКИ ДЛЯ ЗАГРУЗКИ ФАЙЛОВ (до 50 МБ)
# =============================================

# Максимальный размер загружаемого файла — 50 МБ (в байтах)
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 МБ

# Максимальный размер тела запроса (для больших файлов)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Настройки для медиа-файлов (документов)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================
# НАСТРОЙКИ БИТРИКС24
# =============================================

BITRIX24_WEBHOOK = "https://drlk.rfs.ru/rest/205/mkoe2cdimf6len15/"
SMART_PROCESS_ID = 189  # ID вашего смарт-процесса

# =============================================
# НАСТРОЙКИ ПОЧТЫ ДЛЯ СБРОСА ПАРОЛЯ (РАБОТАЮЩИЕ)
# =============================================

# Бэкенд для отправки писем через SMTP Яндекс
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP-сервер Яндекса
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465

# Учётные данные
EMAIL_HOST_USER = "eroproralee@yandex.ru"
EMAIL_HOST_PASSWORD = "njjexcctdygtzbts"  # Пароль приложения

# Настройки безопасности
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

# Email отправителя
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Если письма не отправляются — раскомментируйте эту строку для отладки
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'